### ISSUE TITLE
NOT rechecking after every 20 seconds

### ISSUE THREAD

**Issue by ReyanshPareek** [Suchismit4/Co-Win-Bot#2]
As is visible in the screenshot, it said retrying in 20 seconds - but I guess it never did so later on - ie it checked the slots only once.

I request you to please resolve this issue as the rough general timing of slot availability in the region I live in is very near in time.

PS - I know not a word about coding, let alone python. I simply followed your steps all the while to reach where I am now. So this may not even be an issue from your side - maybe I did something wrong. In that case, please show me the way.

![Screenshot (1706)](https://user-images.githubusercontent.com/84077130/117968987-73fc6180-b344-11eb-8ef8-a5b2aef0c4c4.jpg)

**Comment by Suchismit4** [comment]
Hey there! 

It might be a problem from your side. Could you re run the bot and keep the google chrome window open throughout the process. Also don’t click anything while it’s running in the chrome window it opens. I suggest maximising the window of the chrome. Please let us know asap if it’s fixed, or I will push an update.

**Comment by Suchismit4** [comment]
Hey since then, Aten has found the problem, and we will push a fix tonight. It also fixes the problem where it sometimes shows vaccination centres with no name.

**Comment by Suchismit4** [comment]
![Inked118162506-78a54080-b43e-11eb-9c93-6dc8640f0992_LI](https://user-images.githubusercontent.com/34796828/118163002-0e40d000-b43f-11eb-883c-b9eb5f3f73be.jpg)

Issue fixed & resolved. Pull the latest. Download as a zip, and extract as new. Delete the old folder.

Thanks for reporting. If you like the app, please share it around so people can know about it <3
