### ISSUE TITLE
Can You Help Us Out?

### ISSUE THREAD

**Issue by malayilneil** [Suchismit4/Co-Win-Bot#4]
Hey @Suchismit4 Is there any chance you can share your protected API with the team for their project which I will mention below this message.  

Thank you for your consideration in advance.

https://github.com/bombardier-gif/covid-vaccine-booking/issues

**Comment by Suchismit4** [comment]
The Protected API is accessible to a user. They use it in the logged-in page to book appointment slots in the Co-Win page, if that makes sense :)
