### ISSUE TITLE
Need To Get In Touch

### ISSUE THREAD

**Issue by TheArchitect-666** [Suchismit4/Co-Win-Bot#5]
Have been facing issues with running the bot on my mac. We talked over Reddit. Need to get in touch with you. Preferably, if we can chat over Signal. 

Thanks!

**Comment by Suchismit4** [comment]
Sure
Add me +91 [REDACTED]

**Comment by TheArchitect-666** [comment]
Pinged you up there. Please check.

**Comment by Suchismit4** [comment]
Resolved
